apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hitech-deploy
  name: hitech-deploy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: hitech-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
